default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREDS") { 5 } %>

development:
  <<: *default
  database: resource_allocator_development
  username: postgres
  password: MyStrongPassword123
  host: localhost
  port: 5432

test:
  <<: *default
  database: resource_allocator_test
  username: postgres
  password: MyStrongPassword123
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: resource_allocator_production
    username: resource_allocator
    password: <%= ENV["RESOURCE_ALLOCATOR_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: resource_allocator_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: resource_allocator_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: resource_allocator_production_cable
    migrations_paths: db/cable_migrate
